### ISSUE TITLE
Unable to read user file

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/libstorj-c#121]
### Expected Behavior
```
libstorj-c accepts my decryption key
```

### Actual Behavior

```
Once i type in the decryption key and press enter,  `storj.exe` crashes and i get the following message: 

C:\Users\Meije\Desktop\storj-c>storj list-buckets
Encryption passphrase:
Unable to read user file.

C:\Users\Meije\Desktop\storj-c>
```

**Comment by braydonf** [comment]
I edited the above issue to not include all of the uncompleted template that was copy-and-pasted from bridge.

**Comment by braydonf** [comment]
Okay, I'm able to reproduce with:
```
$ wine src/storj.exe list-buckets
Encryption passphrase: 

Unable to read user file.
wine: Unhandled page fault at address 0x404964 (thread 002e), starting debugger...
```

**Comment by braydonf** [comment]
Okay, the code is giving an error here: https://github.com/Storj/libstorj-c/blob/master/src/storj.c#L539 read_bytes is not as expected.

**Comment by braydonf** [comment]
The segfault is caused by trying to access env, https://github.com/Storj/libstorj-c/blob/master/src/cli.c#L842 needs to be NULL initialized.
