### ISSUE TITLE
Properly configure CA bundle with MinGW build

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/libstorj-c#123]
OS: windows 10

### Expected Behavior
```
I am able to list and add buckets
```

### Actual Behavior

```
C:\Users\Meije\Desktop\storj-c>storj set-auth
Would you like to overwrite the current settings?: [y/n] y
Bridge username (email): meije@storj.io
Password:
Mnemonic: ****
Encryption passphrase:
Again to verify:
Successfully stored username, password, and mnemonic.

C:\Users\Meije\Desktop\storj-c>storj list-buckets
Encryption passphrase:
Request failed with status code: 0
Failed to list buckets.

C:\Users\Meije\Desktop\storj-c>storj add-bucket test
Encryption passphrase:
Failed to add bucket.

C:\Users\Meije\Desktop\storj-c>
```

**Comment by MeijeSibbel** [comment]
C:\Users\Meije\Desktop\storj-c>storj get-info
Storj bridge: https://api.storj.io:443/

Failed to get info.

C:\Users\Meije\Desktop\storj-c>

**Comment by BlackDuck888** [comment]
Build bf87643
On MacOS List-Buckets, Add-Bucket is working correctly. Remove-bucket removes the bucket but with a segmentation 11 error

```
Marcs-MBP:src marcschubert$ ./storj add-bucket test
ID: "e991a3f899536a638f935c75", Name: "test", Storage: 0, Transfer: 0

Marcs-MBP:src marcschubert$ ./storj list-buckets
ID: "c50b7857aafb911104082fca", Name: "usbyyndb", Storage: 0, Transfer: 0
ID: "e991a3f899536a638f935c75", Name: "test", Storage: 0, Transfer: 0

Marcs-MBP:src marcschubert$ ./storj remove-bucket e991a3f899536a638f935c75
Segmentation fault: 11

Marcs-MBP:src marcschubert$ ./storj list-buckets
ID: "c50b7857aafb911104082fca", Name: "usbyyndb", Storage: 0, Transfer: 0
```

**Comment by braydonf** [comment]
@MeijeSibbel It looks like all http calls with and without auth are failing, I wonder if the build doesn't have the CAs added to the build? We should provide a more specific error.

@BlackDuck888 I'm able to reproduce the segment fault on multiple OSs.

**Comment by braydonf** [comment]
@BlackDuck888  Okay, issue with remove-bucket has been fixed. The response body data was empty, which was trying to be parsed and causing the segment fault. And the incorrect error message would have been displayed because the success response code is 204, instead of 200. Tests have been updated.

**Comment by MeijeSibbel** [comment]
@braydonf , i get all the windows build from @aleitner , i don't know if he added the CAs or not.

**Comment by braydonf** [comment]
Okay, we've found some more information on this issue. It's an CA related issue, and working on a fix.

The specific reason why it's failing:
```
Request failed: Problem with the SSL CA cert (path? access rights?)
```

It will work when using `wine src/storj.exe` but it won't when running on windows itself.

**Comment by MeijeSibbel** [comment]
Glad you guys found it, please let us know when the fix is out so that windows users can continue testing, thanks.

**Comment by braydonf** [comment]
Okay, we've found a temporary fix by manually setting `CURLOPT_CAINFO` https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html, and will look into how to fix this without the manual configuration on the user side.
