### ISSUE TITLE
Temp files got not cleared after failure

### ISSUE THREAD

**Issue by BlackDuck888** [Storj/libstorj-c#127]
After a failed download from a file i a public bucket, the "temp"/target file stay in filesystem.

I expect that these files get deleted, after a failure.

```
$ ./storj download-file 2ad575a8f519dc085e21e8a6 fae4935f18e19c774f023b3b /tmp/test.dl
Encryption passphrase: 

Download failure: Bridge request pointer error
$ ls -al /tmp/test.dl 
-rw-r--r--  1 marcschubert  wheel  0 Feb  6 13:26 /tmp/test.dl
```

**Comment by braydonf** [comment]
There is plan to be able to resume incomplete downloads (https://github.com/Storj/libstorj-c/issues/42) from where they left off, so it may not always be the case that these files are cleared. The file on download isn't temporary since it won't be removed once it's complete.

**Comment by BlackDuck888** [comment]
If thats is planned everything is fine for me. Thanks for comment.
