### ISSUE TITLE
Calculate file id by hash of file

### ISSUE THREAD

**Issue by aleitner** [Storj/libstorj-c#129]
We need to stop calculating the file id by file name

**Comment by braydonf** [comment]
I think this will require a change on the bridge to be able to specify the `id` when creating a bucket entry, at around https://github.com/Storj/service-storage-models/blob/master/lib/models/bucketentry.js#L62-L70

**Comment by braydonf** [comment]
I like the idea of using a hash of the file, even if it's salted, so that the integrity of the data can be checked, simply via the fileid.

**Comment by braydonf** [comment]
An hmac of the file has been added on upload and verified on downloads to accomplish the goal of verifying that decryption works successful.
