### ISSUE TITLE
Unnecessary retrieval of mnemonic in cli.c

### ISSUE THREAD

**Issue by mobyvb** [Storj/libstorj-c#57]
In [cli.c lines 519-526](https://github.com/Storj/libstorj-c/blob/master/src/cli.c#L519-L526), the mnemonic is retrieved. Shortly afterwards, if the user is trying to upload a file, [the function `upload_file()` is called](https://github.com/Storj/libstorj-c/blob/master/src/cli.c#L564-L567). In this function, [the mnemonic is retrieved again](https://github.com/Storj/libstorj-c/blob/master/src/cli.c#L76-L81). Wouldn't it be better to pass the mnemonic already retrieved into the `upload_file()` function?

I ask specifically because I am working on issue #23, and the user is prompted for a decryption key every time the mnemonic file needs to be decrypted. So `storj upload-file` ends up prompting the user twice for this key.

Also, as a side note, `upload_file()` exits the program directly if there is no mnemonic. But wouldn't it be better to return an error code and let the caller handle that?

**Comment by braydonf** [comment]
Yes, the mnemonic in upload doesn't need to be there, and the mnemonic for the upload can use env for the mnemonic.
