### ISSUE TITLE
Add additional setup methods to CLI

### ISSUE THREAD

**Issue by braydonf** [Storj/libstorj-c#87]
A couple of ideas:
- `generate-seed` to create a new mnemonic with 128 or 256 bits of entropy. This could also be called `generate-mnemonic`, or `generate-key`.
- `export-seed` to be able to export the mnemonic to another device. Some other names could be `print-seed` or `export-auth` *(which could also include bridge password)*.

**Comment by mobyvb** [comment]
- [ ] Update `register` to generate a new mnemonic when a user is created. Should also store these locally and encrypted like `set-auth` does
- [ ] Rename `set-auth` to `import-auth`. It should ask for username, password, and mnemonic, and verify mnemonic when it is entered.
- [ ] Create `export-auth` which prints out locally stored username, password, and mnemonic.

**Comment by braydonf** [comment]
This is partially completed, and is just missing saving on register https://github.com/Storj/libstorj-c/blob/master/src/cli.c#L534-L536
